### ISSUE TITLE
模型支持（text+image) to video吗？

### ISSUE THREAD

**Issue by XHB-ZMM** [Vchitect/Vchitect-2.0#10]

**Comment by nourakhy** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by XHB-ZMM** [comment]
> try this https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic If you don't have the c compliator, install it.(gcc or clang)

这是个什么？可执行程序吗？

**Comment by WeichenFan** [comment]
Hi, only t2v model has been released for now.
