### ISSUE TITLE
官网上那个Try It是2.0的效果吗，怎么那么垃圾 https://vchitect.intern-ai.org.cn/

### ISSUE THREAD

**Issue by TZYSJTU** [Vchitect/Vchitect-2.0#12]
逆天bug？ 

https://github.com/user-attachments/assets/5f73e0ee-3010-421a-a89d-ee488bee8659

伪影一塌糊涂  

https://github.com/user-attachments/assets/35009c68-6964-4d3a-8ce4-88397271f52d

螃蟹走路？  

https://github.com/user-attachments/assets/990ff447-3560-40fa-ad90-40f407e24196

影分身？ 

https://github.com/user-attachments/assets/ee7388b9-f087-4f73-8e29-7292e484e1ee

**Comment by WeichenFan** [comment]
Some 16:9 images are recommended.
