### ISSUE TITLE
Inference for Image2Video & Dynamic Degree of the model

### ISSUE THREAD

**Issue by C00reNUT** [Vchitect/Vchitect-2.0#2]
Hello, 

thank you for making this public! 

Could you maybe include example command for img2vid generation as seen on your https://vchitect.intern-ai.org.cn/#section3 website? 

Also is there any parameter that controls 'Dynamic Degree - movability' of the model?

Also some details for VRAM info for each resolution and video length would be nice!

Thanks!

**Comment by WeichenFan** [comment]
Hi C00reNUT,

Thanks for your interest.

The I2V model has not been released yet. The current model can only support text2vid generation. We don't support dynamic control for now, but will look into this in the future! We'll add more info shortly!
