### ISSUE TITLE
Runtime error: cannot import name 'PrepareModuleOutput' from 'torch.distributed.tensor.parallel'

### ISSUE THREAD

**Issue by yuanzhi-zhu** [Vchitect/Vchitect-2.0#5]
Thank your for opening source such a great work

I got the above error when running the inference code.

I installed the env followed the instructions in Readme, and it seems that we need PyTorch > 2.1 to have PrepareModuleOutput in torch.distributed.tensor.parallel.

Did I missed something here?

**Comment by WeizhenEricFang** [comment]
Have you got any solution? I got the same error

**Comment by yuanzhi-zhu** [comment]
@WeizhenEricFang Just install PyTorch > 2.1 and resolve some other conflicts
