### ISSUE TITLE
实测和官网差距较大

### ISSUE THREAD

**Issue by fuchao01** [Vchitect/Vchitect-2.0#9]
请问这个开源的t2v 2B模型和官网发布的是一样的吗？实际测是来看，效果差距还是挺大的

**Comment by ChenyangSi** [comment]
Hi @fuchao01 ，
Thanks for your interest!

The videos on our website showcase both T2V and I2V results.  The base T2V model supports generating videos with resolutions up to 720x480 at 8fps. You can use [VEnhancer](https://github.com/Vchitect/VEnhancer) to upscale the resolution to 2K and interpolate the frame rate to 24fps. For more details, including the prompt and arguments for inference, please refer to the README. We have updated the "num_inference_steps".
